title: "Welcome!"
author: "Xiang 'Jacob' Yan"
description: "Welcome!"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: flase           # adds a gray frame to the site
show_sidebar: true       # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "About", file: "index.md"}
  #- {title: "CV", url: "https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jacobyan0/jacobyan0.github.io/master/Yan_CV.pdf"}
  - {title:"People", file: "people.md"} 
  - {file: "projects.md"}
  #- {file: "publications.md"}
  #- {file: "invitedtalks.md"}
  - {file: "software.md"}
  - {file: "teaching.md"}
  - {file: "openpositions.md"}
  #- {file: "media.md"}
  #- {file: "news.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:xjacobyan@gmail.com"}
  - {title: GoogleScholar, icon: user-graduate, url: "https://scholar.google.com/citations?user=5A-NXMsAAAAJ&hl=en"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/xiang-jacob-yan-3a526781/"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Xiang-Yan-8"}
  #- {title: Twitter, icon: twitter-square, url: "https://twitter.com/JacobYan3"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-sitemap
